Update .github/workflows/release_npmjs.yaml

diff --git a/.github/workflows/release_npmjs.yaml b/.github/workflows/release_npmjs.yaml
--- a/.github/workflows/release_npmjs.yaml
+++ b/.github/workflows/release_npmjs.yaml
@@ -3,7 +3,8 @@ name: release_npmjs
 on:
   push:
     tags:
-      - 'v*.*.*'
+      - 'v*'
+  workflow_dispatch:
 
 jobs:
   release:
@@ -12,6 +13,17 @@ jobs:
       contents: read
       id-token: write
     steps:
+      - name: Check tag name
+        run: |
+          if [[ "${GITHUB_REF_TYPE}" != "tag" ]]; then
+            echo "This action only runs on tag events: ${GITHUB_REF_TYPE}"
+            exit 1
+          fi
+          TAG_NAME=$(echo "${GITHUB_REF_NAME}" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$')
+          if [[ "${TAG_NAME}" == "" ]]; then
+            echo "Invalid tag name: ${GITHUB_REF_NAME}"
+            exit 1
+          fi
       - name: Checkout
         uses: actions/checkout@v5
       - name: Setup Node
